spring:
  application:
    name: KHelpServer
  profiles:
    active: dev
  config:
    import:
      - classpath:database-${spring.profiles.active}.yaml
      - classpath:mongodb-${spring.profiles.active}.yaml
      - classpath:jwt-${spring.profiles.active}.yaml