spring:
  application:
    name: KHelpServer
  profiles:
    active: dev
  config:
    import:
      - classpath:${spring.profiles.active}/database.yaml
      - classpath:${spring.profiles.active}/mongodb.yaml
      - classpath:${spring.profiles.active}/redis.yaml
      - classpath:${spring.profiles.active}/jwt.yaml